#!/usr/bin/env sh

# set config home
if [ -z "$XDG_CONFIG_HOME" ]; then
  echo '$XDG_CONFIG_HOME not set, falling back to `~/.config`'
  export XDG_CONFIG_HOME="$HOME/.config"
fi

# set cache path
if [ -z "$XDG_CACHE_HOME" ]; then
  echo '$XDG_CACHE_HOME not set, falling back to `~/.cache`'
  export XDG_CACHE_HOME="$HOME/.cache"
fi

step() {
  echo '\033[0;33m'$1 $2'\033[0m'
}

run() {
  dir="$1"
  if [ -d "$dir" ]; then
    install="$dir/install"
    if [ -f "$install" ]; then
      step run "$install"
      cat "$install" | sed -e '/^ *#/ d' -e '/^$/ d' -e 's/^\(.*\)/  \1/'
    fi
  fi
}

echo "dry-running:

\$HOME="$HOME"
\$XDG_CONFIG_HOME=$XDG_CONFIG_HOME
\$XDG_CACHE_HOME=$XDG_CACHE_HOME
"

# intialize cache dir
step mkdir "$XDG_CACHE_HOME"

# run global install script first
run "$XDG_CONFIG_HOME/install"

if [ $# -gt 0 ]; then
  # run every install script in arguments
  for arg in "$@"; do
    dir="$XDG_CONFIG_HOME/$arg";
    run "$dir"
  done
else
  # run every install script
  for dir in "$XDG_CONFIG_HOME"/*; do
    run $dir;
  done
fi

# vim: ft=sh
